### ISSUE TITLE
Unable to skip TLS Verification for mysqlrouter

### ISSUE THREAD

**Issue by hellstrikes13** [rluisr/mysqlrouter_exporter#1]
Hello,
how can I skip TLS verification for mysqlrouter_exporter chart

I m using SELF Signed CERTs on my mysqlrouter

`Aug 19 08:29:40 p35-bastion.someorg.com mysqlrouter_exporter[10180]: 2020/08/19 08:29:40 failed to create mysql router client. err: Get "https://p35-bastion.someorg.com:8443/api/20190715/swagger.json": x509: certificate signed by unknown authority`

i don't see any place to add 'insecure_skip_verify' flag for this exporter service

```
mysqlrouter_exporter --help
--port        Listen port. Default 49152
--version     Show version
```

**Comment by rluisr** [comment]
This exporter depends on [rluir/mysqlrouter-go](https://github.com/rluisr/mysqlrouter-go).

I'll update mysqlrouter-go and mysqlrouter_exporter by the end of this week.

**Comment by rluisr** [comment]
@hellstrikes13 Please try `v2.2.1` and using `--skip-tls-verify` flag.

**Comment by hellstrikes13** [comment]
Thank you for quick  support
Everything works now. 👍
