### ISSUE TITLE
mysqlrouter_exporter CPU utilisation

### ISSUE THREAD

**Issue by hellstrikes13** [rluisr/mysqlrouter_exporter#11]
Hi,
We are again hitting the same issue of HIGH CPU & Memory utilisation
0efd986164:~$ grep mysqlrouter_metadata_status /tmp/myrtr | wc -l
575598

Over the time, this metric is accumulating and there is gradual increase in cpu, so we want to cut down metric router_metadata_status.

**so can we just have  1 skip flag:**
--skip=<arguments would be the metric names separate by commas >
so in this case we don't need 3 to 4 skip flag and in turn reduces the dev effort of creating more flags
NOTE:
This is nothing to do with HIGH traffic coz rest of prometheus exporter are not showing so much high CPU utilisation etc. 
we are having docker image of mysqlrouter_exporter running on kubernetes POD
we have given max resources to this mysqlrouter_exporter POD so that it doesn't run out of capacity while collecting metrics nor it restarts at any moment.
below is the configuration of running mysqlrouter_exporter:

```
/opt/mysqlrouter_exporter --skip-tls-verify \
                          --skip.collect.route.connections.byte_from_server \
			  --skip.collect.route.connections.byte_to_server \
			  --skip.collect.route.connections.time_started \
			  --skip.collect.route.connections.time_connected_to_server \
                          --skip.collect.route.connections.time_last_sent_to_server \
			  --skip.collect.route.connections.time_received_from_server \
			  --listen-port=8444
```
so instead can we just have 1 flag
--skip="metrics1,metrics2,metrics3 etc"
 mysql-router_exporter will stop collecting these all metrics

Since we are monitoring each and every k8s pod we are always alerted w.r.t high cpu utilisation by this mysqlrouter_exporter POD.
Let me know if anything else is more needed from my end or any workaround you can provide.

Thank you.

**Comment by rluisr** [comment]
Yes, The `timeLastRefreshSucceeded` of `/metadata/<name>/status` is updated every time, So you are hitting CPU usage is high.

I'm walking for adding a skip flag.

Thanks for sharing that.

**Comment by rluisr** [comment]
I released `v3.0.0`. It hanged flag type `skip.~` -> `collect.~`.

> so instead can we just have 1 flag
--skip="metrics1,metrics2,metrics3 etc"

Could you create a new issue? I want to separate.

**Comment by hellstrikes13** [comment]
Sure @rluisr  will create a new issue

**Comment by hellstrikes13** [comment]
new issue created: "Need a skip flag for mysqlrouter_exporter #13"
