### ISSUE TITLE
Need a skip flag for mysqlrouter_exporter

### ISSUE THREAD

**Issue by hellstrikes13** [rluisr/mysqlrouter_exporter#13]
Hi,
We need new flag --skip="metrics list separated by comma that are to be skippped"
e.g --skip=metrics1,metrics2,metrics3

There are some metrics which are creating lot of noise and consuming lot of system resources such as CPU,
 so we wish to scrap out all those metrics hence a skip flag.

**Comment by rluisr** [comment]
PR #9
