### ISSUE TITLE
Is it possible to use TLS authentication to connect mysqlrouter?

### ISSUE THREAD

**Issue by fromhans** [rluisr/mysqlrouter_exporter#14]
Hi, Thanks for making this exporter.

I have difficulties in connecting mysqlrouter.

I am trying to using ssl certification like below.  
But I don't know how to configure mysqlrouter_exporter service file when using ssl certification.
when using ssl certification in mysqlrouter, how should i setup starting flag of exporter or environment variables? 
It looks like there is no pem file environment variables (only URL, PASS, USER variables exists)

* mysqlrouter.conf
[http_server]
port=11002
ssl=1
ssl_cert=/var/lib/mysqlrouter/router-cert.pem
ssl_key=/var/lib/mysqlrouter/router-key.pem

* [Service] in mysqlrouter_exporter.service file
[Service]
Type=simple
Restart=always
RestartSec=15
Environment=\"MYSQLROUTER_EXPORTER_URL=http://127.0.0.1:10001\"
Environment=\"MYSQLROUTER_EXPORTER_USER=histudy\"
Environment=\"MYSQLROUTER_EXPORTER_PASS=dailystudy2*\"
ExecStart=/opt/mysqlrouter_exporter/mysqlrouter_exporter \\
--listen-port=10102 \\
--collect.metadata.status \\
--collect.route.connections.byte_from_server \\
--collect.route.connections.byte_to_server \\
--collect.route.connections.time_started \\
--collect.route.connections.time_connected_to_server \\
--collect.route.connections.time_received_from_server

**Comment by fromhans** [comment]
Hi @rluisr 
Is there any other way to use tls verification? 
I don't want to skip tls verification. 
I am asking how to config public/private key file in this exporter.

**Comment by rluisr** [comment]
We need to add a function for supporting private certificates.
ref: https://github.com/rluisr/mysqlrouter-go/blob/10d10b45806fcb613fb45b8c73bf918909f9facb/request.go#L11

But I have no time to work on this. Or welcome PR.

**Comment by rluisr** [comment]
now I'm working https://github.com/rluisr/mysqlrouter-go/issues/6
