### ISSUE TITLE
failed to create mysql router client

### ISSUE THREAD

**Issue by HapipHaekal** [rluisr/mysqlrouter_exporter#21]
Hi
I'm having trouble running mysql router exporter
mysqlrouter uses certificates, so I tried using `--skip-tls-verify` like this :

mysqlrouter_exporter.service :
> [Service]
> Type=simple
> Environment="MYSQLROUTER_EXPORTER_URL=http://10.10.10.80:8443"
> ExecStart=/usr/local/bin/mysqlrouter_exporter \
> --skip-tls-verify

mysqlrouter.conf : 
> [http_server]
> port=8443
> ssl=1
> ssl_cert=/var/lib/mysqlrouter/router-cert.pem
> ssl_key=/var/lib/mysqlrouter/router-key.pem

When I restart there is a problem like this, `systemctl status mysqlrouter_exporter -l` :

```
● mysqlrouter_exporter.service - mysqlrouter-exporter
   Loaded: loaded (/etc/systemd/system/mysqlrouter_exporter.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Mon 2022-12-05 17:48:57 WIB; 9s ago
     Docs: https://github.com/rluisr/mysqlrouter-exporter
  Process: 80964 ExecStart=/usr/local/bin/mysqlrouter_exporter --skip-tls-verify (code=exited, status=1/FAILURE)
 Main PID: 80964 (code=exited, status=1/FAILURE)

Dec 05 17:48:56 mysql-router-test2 systemd[1]: Started mysqlrouter-exporter.
Dec 05 17:48:57 mysql-router-test2 mysqlrouter_exporter[80964]: 2022/12/05 17:48:57 failed to create mysql router client. err: Get "http://10.10.10.80:8443/api/20190715/swagger.json": EOF
Dec 05 17:48:57 mysql-router-test2 systemd[1]: mysqlrouter_exporter.service: main process exited, code=exited, status=1/FAILURE
Dec 05 17:48:57 mysql-router-test2 systemd[1]: Unit mysqlrouter_exporter.service entered failed state.
Dec 05 17:48:57 mysql-router-test2 systemd[1]: mysqlrouter_exporter.service failed.
```

**Comment by rluisr** [comment]
Hi @HapipHaekal 

Could you try this command and share the result?

`curl https://localhost:8443/api/20190715/swagger.json -k`

**Comment by rluisr** [comment]
I've found the wrong environment variable.
Maybe you've forgot `s` -> `https`
