### ISSUE TITLE
mysqlrouter_route_health always health even mysqlrouter is stopped

### ISSUE THREAD

**Issue by githubTravel** [rluisr/mysqlrouter_exporter#40]
The exporter I used is the latest version 4.0.5
mysqlrouter version: MySQL Enterprise - Commercial 8.0.34

When I stopped mysqlrouter, still get all the route are health.
Please help to look into this issue.

Thank you.

**Comment by rluisr** [comment]
Thank you for reporting an issue.

I release v4.0.6 and please check this version.

Reopen this issue if not solved!
