### ISSUE TITLE
Ungraceful shutdown of mysql-router-exporter can lead to connections in TIME_WAIT; missing graceful shutdown of server

### ISSUE THREAD

**Issue by shayancanonical** [rluisr/mysqlrouter_exporter#59]
## Issue
The exporter starts a server on `listen-port` using [http.ListenAndServe](https://github.com/rluisr/mysqlrouter_exporter/blob/master/main.go#L351). However, there is no attempt at a graceful shutdown when a SIGTERM is received (see [this post](https://stackoverflow.com/questions/39320025/how-to-stop-http-listenandserve) for some ideas of how a SIGTERM can be reacted with a `server.Shutdown()`)

We have an [issue in our project](https://github.com/canonical/mysql-router-k8s-operator/issues/219) where we use this project (mysqlrouter_exporter). As the trace in the issue indicates, we run into `bind address in use` error intermittently when we start exporter, stop it and then restart it. Further digging revealed that when we stop exporter, sometimes, due to an ungraceful shutdown, we have connections in `TIME_WAIT`:

```
root@mysql-router-k8s-0:/# netstat -nat  | grep 49152
tcp        0      0 10.1.241.229:49152      10.1.241.230:3306       TIME_WAIT
```
It is exactly under these conditions that we run into the `bind address in use` error. When the 

## Suggested Solution
 To gracefully shutdown the server as indicated by the [above linked post](https://stackoverflow.com/questions/39320025/how-to-stop-http-listenandserve) when a SIGTERM is received

## Potential followups
I will attempt to create a PR with a proposed solution for this issue

**Comment by rluisr** [comment]
@shayancanonical Thank you for reporting.

I released a new version v5.0.1. If the problem has not been resolved, re-open it.
