### ISSUE TITLE
Need command line options  to scrap particular metrics from mysql-router-exporter

### ISSUE THREAD

**Issue by hellstrikes13** [rluisr/mysqlrouter_exporter#8]
We are using mysqlrouter_exporter
version: 2.2.1 commit: eb1138d0ba64ba8fda046379bfc2ac0d749276a8 date: 2020-08-20T05:11:26Z

we are seeing HIGH amount of CPU usage when mysql-router_exporer is scraping the metrics

I can see 37,418 lines of this particular metric
cat route_metric.txt | grep route_connections_time_started -c 
37418
E.g:
route_connections_time_started{destination_address="mysql-host1:3306",name="some_cluster",router_hostname="mysql-router-7465d4cb76-xmz4s",source_address="10.10.10.20:60678"} 1.614528416e+12

i don't want this particular metric at all 
how do i scrap out this metric

sh-4.2# ./mysqlrouter_exporter --help
--port        		Listen port. Default 49152
--version     		Show version
--skip-tls-verify	Skip TLS Verification

Need some more flags to scrap in the metrics i need
just like how mysqld_exporter has it -> https://github.com/prometheus/mysqld_exporter

**Comment by rluisr** [comment]
Thank you for reporting the problem.

I released v2.3.0. Please try it.
PR #9

**Comment by rluisr** [comment]
ref: https://github.com/rluisr/mysqlrouter_exporter#collector-flags

**Comment by rluisr** [comment]
If you still have problems, please let me know.

**Comment by hellstrikes13** [comment]
Thanks a lot rluisr for prompt action. 
it worked fine.

**Comment by rluisr** [comment]
Thank you for confirming :-)
